[profile.default]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
remappins = [
    '@chainlink/contracts/=../lib/chainlink-brownie-contracts/contracts',
    '@solmate=../lib/solmate/src',
]
# use this instead of ffi = true
src = "src"
out = "out"

libs = ["lib"]

[fuzz]
runs = 300
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
